#!/bin/sh

BASEDIR=$PWD

echo "- Determine OS and set package manager..."
if [[ "$OSTYPE" == "darwin"* ]]
then
    echo "OS: MacOS $OSTYPE"
    PKGMGR="brew install"
elif [[ "$(cat /etc/issue)" == "Ubuntu"* ]] || [[ "$(cat /etc/issue)" == "Debian"* ]] 
then
    echo "OS: $OSTYPE"
    PKGMGR="sudo apt install "
else
    echo "ERROR: Unsupported OS, change the script yourself"
    exit 1
fi


# attempt to clone tmux
# on success it should overwrite the existing .tmux conf
echo "- Update tmux if repo still exists"
cd .tmux
git pull
cd $BASEDIR

echo "- Linking .vim/ ..."
ln -sf $BASEDIR/.vim $HOME/.vim

echo "- Linking .vimrc ..."
ln -sf $BASEDIR/.vimrc $HOME/.vimrc

echo "- Linking .tmux ..."
ln -sf $BASEDIR/.tmux/.tmux.conf $HOME/.tmux.conf
cp $BASEDIR/.tmux/.tmux.conf.local $HOME

echo "-  Install zsh if it doesn't exist"
which zsh
if [ $? -ne 0 ]
then
    echo "zsh has not been installed, will install now"
    $OSTYPE zsh
else
    echo "zsh has been installed :)"
fi

echo "- Linking .zshrc ..."
ln -sf $BASEDIR/.zshrc $HOME/.zshrc
