#!/bin/sh

BASEDIR=$PWD

# attempt to clone tmux
# on success it should overwrite the existing .tmux conf
cd .tmux
git pull
cd $BASEDIR

echo "Linking .vim/ ..."
ln -sf ./.vim $HOME/.vim 

echo "Linking .vimrc ..."
ln -sf ./.vimrc $HOME/.vimrc 

echo "Linking .tmux ..."
ln -sf .tmux/.tmux.conf $HOME/.tmux.conf 
cp .tmux/.tmux.conf.local .
