#!/bin/sh

BASEDIR=$PWD

# attempt to clone tmux
# on success it should overwrite the existing .tmux conf
cd .tmux
git pull
cd $BASEDIR

echo "Linking .vim/ ..."
ln -sf $BASEDIR/.vim $HOME/.vim

echo "Linking .vimrc ..."
ln -sf $BASEDIR/.vimrc $HOME/.vimrc

echo "Linking .tmux ..."
ln -sf $BASEDIR/.tmux/.tmux.conf $HOME/.tmux.conf
cp $BASEDIR/.tmux/.tmux.conf.local $HOME
